version: "3"

services:
  app:
    image: docker-report-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./components:/app/components
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
      - ./_nav.tsx:/app/_nav.tsx
