import Head from "next/head";
import { PropsWithChildren, useEffect } from "react";
import Sidebar from "../Sidebar/Sidebar";
import Footer from "./Footer";
import Header from "./Header";
import ToggleThemeHeader from "./ToggleThemeHeader";

export default function DashboardLayout ({children}: PropsWithChildren) {
  return (
    <>
      <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Sidebar />

      <div className="relative md:ml-64 bg-mac-light-background dark:bg-mac-dark-background h-screen">
        {/* <Header /> */}
        <ToggleThemeHeader />
        {children}
        <Footer />
        {/* <main className="container mx-auto px-4 top-5 md:px-10 w-full -m-24">
          {children}  
          <Footer />
        </main> */}
        
      </div>
    </>
  );
}